version: '3'

services:
  storefront:
      container_name: project-name-storefront
      build: ./storefront
      ports:
        - "3120:3000"
      env_file:
        - ./storefront/.env
      restart: always

  api:
      container_name: project-name-api
      build: ./api
      ports:
        - "3130:3000"
      restart: always
      env_file:
        - ./api/.env
      depends_on:
        - postgres
        - redis
      networks:
        - project_name

  redis:
    image: redis:latest
    ports:
      - "5379:6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
        - project_name

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db_name
    ports:
      - "5672:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
        - project_name

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
        - project_name

volumes:
  redis-data:
  postgres-data:
  elasticsearch-data:

networks:
  project_name:
